### ISSUE TITLE
Which documentation?

### ISSUE THREAD

**Issue by dlebauer** [OlssonF/NEON-forecast-challenge-workshop#12]
I'm reviewing the [JOSE submission](https://github.com/openjournals/jose-reviews/issues/259#issuecomment-2384261267) 

This GitHub repository has a link to https://projects.ecoforecast.org/neon4cast-docs/

<img width="325" alt="image" src="https://github.com/user-attachments/assets/71178907-4cb0-4b1b-a411-b244bd33d885">

But that page tells reader to visit www.neon4cast.org, which in turn redirects to to https://projects.ecoforecast.org/neon4cast-ci/instructions.html.

What is the difference between these pages? Should the link on the repository be changed?

**Comment by OlssonF** [comment]
The link originally listed was to a previous version of the documentation which has been superseded. I've updated the materials to the https://projects.ecoforecast.org/neon4cast-ci/ (the most up-to-date link)to avoid confusion as well is in the main .Rmd
Thanks for pointing this out David.
