### ISSUE TITLE
Add Community Guidelines 

### ISSUE THREAD

**Issue by dlebauer** [OlssonF/NEON-forecast-challenge-workshop#13]
Review criteria for JOSE https://github.com/openjournals/jose-reviews/issues/259 include:

> Are there clear guidelines for third parties wishing to 1) Contribute to the module 2) Report issues or problems with the module 3) Seek support

Typically I would expect this information to be provided in either CONTRIBUTING.md or .github/CONTRIBUTING.md. See https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file

**Comment by skmorgane** [comment]
Review for JOSE: openjournals/jose-reviews#259
I could not find community guidelines either. Figure I'd just put that here instead of open a redundant issue for efficiency.

**Comment by OlssonF** [comment]
Thanks for identifying this omission. We have now added a [contributing.md](https://github.com/OlssonF/NEON-forecast-challenge-workshop/blob/main/Contributing.md ) to the root directory.
