### ISSUE TITLE
Pulling Docker image eco4cast/rocker-neon4cast returns 'no match for platform in manifest'

### ISSUE THREAD

**Issue by dlebauer** [OlssonF/NEON-forecast-challenge-workshop#15]
## Problem

Following the README when I run

```
docker run --rm -ti -e PASSWORD=yourpassword \
  -p 8787:8787 eco4cast/rocker-neon4cast
```

> docker: Error response from daemon: no match for platform in manifest: not found.

If I Google around I (don't quite understand but) see I might add `--platform=linux/amd64`:

```
dockerpull --platform=linux/amd64 eco4cast/rocker-neon4cast
```

but then the `docker run` command returns:

> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
rosetta error: Rosetta is only intended to run on Apple Silicon with a macOS host using Virtualization.framework with Rosetta mode enabled

Environment:
- Docker version 26.1.4, build 5650f9b
- Apple M1 Pro with MacOS 15.0

## Resolution

- update README with instructions that will work on MacOS with M* processors?

**Comment by rqthomas** [comment]
@dlebauer Thanks so much for your review!

The following works for pre-macOS 15. 
```
docker run --platform linux/amd64 --rm -ti -e PASSWORD=yourpassword -p 8787:8787 eco4cast/rocker-neon4cast
```
In macOS 15 the transition software (Rosetta) is not installed by default and needs to be installed using:

```
softwareupdate --install-rosetta
```

Then you can run the `docker run` command above.  Does this work for you?

**Comment by OlssonF** [comment]
Thank you David, we have added additional instructions for Mac users about using docker into the README:

#### Note for Mac users

If you are running Docker on ARM architecture (e.g., Apple Silicon M chips), the following Docker command is needed

```         
docker run --platform linux/amd64 --rm -ti -e PASSWORD=yourpassword -p 8787:8787 eco4cast/rocker-neon4cast
```

If you are using macOS Sequoia (and future macOS versions), you may get this error:

```         
rosetta error: Rosetta is only intended to run on Apple Silicon with a macOS host using Virtualization.framework with Rosetta mode enabled
```

If you get this error, you will need to install `rosetta` before running the docker command above.

```         
softwareupdate --install-rosetta
```

**Comment by dlebauer** [comment]
that works, thanks!
