### ISSUE TITLE
NEON_..._aquatics.Rmd Add Repo Name

### ISSUE THREAD

**Issue by skmorgane** [OlssonF/NEON-forecast-challenge-workshop#17]
Review comment for JOSE: https://github.com/openjournals/jose-reviews/issues/259

This is a minor comment:

Line 111: Information on the NEON sites can be found in the `NEON_Field_Site_Metadata_20220412.csv` file on GitHub.

This lesson has a couple of difference repos that it pulls from. I would suggest modifying this sentence to:

 Information on the NEON sites can be found in the `NEON_Field_Site_Metadata_20220412.csv` file in the eco4cast repo on GitHub.

I know it is referenced in the code immediately afterwards but novices won't understand what they're seeing and will go instinctively to the workshop repo.

**Comment by OlssonF** [comment]
That's a good point. We have updated the line as suggested:
