### ISSUE TITLE
Registration link issue

### ISSUE THREAD

**Issue by skmorgane** [OlssonF/NEON-forecast-challenge-workshop#18]
Review for JOSE openjournals/jose-reviews#259

This is a minor comment:
In NEON_forecast_..._aquatics.Rmd, line 498

The link (https://nd.qualtrics.com/jfe/form/SV_9MJ29y2xNrBOjqZ) to register participation does not work. I suspect that is because it is only made active when a workshop is being presented? But if this is being used for classes or individual self-directed learning, people are going to try to use that link. I don't know how you want to handle it, but think it is worth dealing with now to avoid myriad confused emails in the future.

**Comment by OlssonF** [comment]
Thank you for noting this! The link was recently updated. We have now modified the materials.
